### ISSUE TITLE
Equal sign in arithmetic expressions

### ISSUE THREAD

**Issue by satos** [Okuajub/CHIPS#1] opened 2024-01-15 00:34 UTC
I have discovered this project of yours. It is a very nice achievement! I think it is the perfect template for Kawari in the English-speaking world.

By the way, looking at your code, I noticed that you use "=" in many comparison expressions in arithmetic expressions (In other words, inside $[]). 
The KIS specification uses "==" in comparison expressions. 
Perhaps this part is not working properly. Please check.

**Comment by Okuajub** [comment] 2024-01-15 04:45
Thank you! Publishing the template has taken several months of work, as there are few English Kawari resources. so I am glad you like it!

Don't worry, while "==" is more standard, "==" and "=" are interchangeable in KIS due to "=" not being used for assigning variables. I learned it initially in the [documentation](https://kawari.sourceforge.net/8.2.5/programming_2.html#prg2_5), where they are listed as the same. As far as I can tell, everything is working as intended.

However, it could be beneficial for me to change this to make it consistent with how it is normally written in other Ghosts. That way, it is less confusing.

Thank you for your feedback, it's appreciated.

**Comment by Okuajub** [comment] 2024-01-17 04:35
Addressed in the [last fix](https://github.com/Okuajub/CHIPS/commit/74b49aae5182565af1cb0faa735bf35e42823eef), all "=" should be changed to "==" for consistency and clarity. They will be written this way going forward, too.

**Closed as completed by Okuajub** 2024-01-17 04:35 UTC
